class Autogenerated {
  List<Churches> churches;

  Autogenerated({this.churches});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['churches'] != null) {
      churches = new List<Churches>();
      json['churches'].forEach((v) {
        churches.add(new Churches.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.churches != null) {
      data['churches'] = this.churches.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Churches {
  String name;
  String formattedAddress;
  Geometry geometry;
  List<HoursOpen> hoursOpen;
  List<BusyHours> busyHours;
  List<QuietHours> quietHours;

  Churches(
      {this.name,
      this.formattedAddress,
      this.geometry,
      this.hoursOpen,
      this.busyHours,
      this.quietHours});

  Churches.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    formattedAddress = json['formatted_address'];
    geometry = json['geometry'] != null
        ? new Geometry.fromJson(json['geometry'])
        : null;
    if (json['hours_open'] != null) {
      hoursOpen = new List<HoursOpen>();
      json['hours_open'].forEach((v) {
        hoursOpen.add(new HoursOpen.fromJson(v));
      });
    }
    if (json['busy-hours'] != null) {
      busyHours = new List<BusyHours>();
      json['busy-hours'].forEach((v) {
        busyHours.add(new BusyHours.fromJson(v));
      });
    }
    if (json['quiet-hours'] != null) {
      quietHours = new List<QuietHours>();
      json['quiet-hours'].forEach((v) {
        quietHours.add(new QuietHours.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['formatted_address'] = this.formattedAddress;
    if (this.geometry != null) {
      data['geometry'] = this.geometry.toJson();
    }
    if (this.hoursOpen != null) {
      data['hours_open'] = this.hoursOpen.map((v) => v.toJson()).toList();
    }
    if (this.busyHours != null) {
      data['busy-hours'] = this.busyHours.map((v) => v.toJson()).toList();
    }
    if (this.quietHours != null) {
      data['quiet-hours'] = this.quietHours.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Geometry {
  String lat;
  String lng;

  Geometry({this.lat, this.lng});

  Geometry.fromJson(Map<String, dynamic> json) {
    lat = json['lat'];
    lng = json['lng'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['lat'] = this.lat;
    data['lng'] = this.lng;
    return data;
  }
}

class HoursOpen {
  List<String> monday;
  List<String> tuesday;
  List<String> wednesday;
  List<String> thursday;
  List<String> friday;
  List<String> saturday;
  List<String> sunday;

  HoursOpen(
      {this.monday,
      this.tuesday,
      this.wednesday,
      this.thursday,
      this.friday,
      this.saturday,
      this.sunday});

  HoursOpen.fromJson(Map<String, dynamic> json) {
    monday = json['Monday'].cast<String>();
    tuesday = json['Tuesday'].cast<String>();
    wednesday = json['Wednesday'].cast<String>();
    thursday = json['Thursday'].cast<String>();
    friday = json['Friday'].cast<String>();
    saturday = json['Saturday'].cast<String>();
    sunday = json['Sunday'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Monday'] = this.monday;
    data['Tuesday'] = this.tuesday;
    data['Wednesday'] = this.wednesday;
    data['Thursday'] = this.thursday;
    data['Friday'] = this.friday;
    data['Saturday'] = this.saturday;
    data['Sunday'] = this.sunday;
    return data;
  }
}

class BusyHours {
  List<int> monday;
  List<int> tuesday;
  List<int> wednesday;
  List<int> thursday;
  List<int> friday;
  List<int> saturday;
  List<int> sunday;

  BusyHours(
      {this.monday,
      this.tuesday,
      this.wednesday,
      this.thursday,
      this.friday,
      this.saturday,
      this.sunday});

  BusyHours.fromJson(Map<String, dynamic> json) {
    monday = json['Monday'].cast<int>();
    tuesday = json['Tuesday'].cast<int>();
    wednesday = json['Wednesday'].cast<int>();
    thursday = json['Thursday'].cast<int>();
    friday = json['Friday'].cast<int>();
    saturday = json['Saturday'].cast<int>();
    sunday = json['Sunday'].cast<int>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Monday'] = this.monday;
    data['Tuesday'] = this.tuesday;
    data['Wednesday'] = this.wednesday;
    data['Thursday'] = this.thursday;
    data['Friday'] = this.friday;
    data['Saturday'] = this.saturday;
    data['Sunday'] = this.sunday;
    return data;
  }
}